config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "up" => "rails/health#show", as: :rails_health_check
  root "homes#index"
  resources :profile, only: [:create, :update,]
  resources :posts, only: [:create, :post, :update, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :comments, only: [:create, :update, :destroy]
  resources :follows, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :likes, as: :likeable
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, foreign_key: 'follower_id', class_name: 'User'
  belongs_to :following, foreign_key: 'following_id', class_name: 'User'

  validate :different_follower_and_following

  private

  def different_follower_and_following
    if follower_id == following_id
      errors.add(:base, "Follower and Following can't be the same")
    end
  end
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :likeable, polymorphic: true
    belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :likes, as: :likeable
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  validates :user_id, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :profile
  has_many :posts
  has_many :comments
  has_many :likes
  has_many :follows

  has_many :follower_relationships, foreign_key: :following_id, class_name: "Follow"
  has_many :followers, through: :follower_relationships, source: :follower

  has_many :following_relationships, foreign_key: :follower_id, class_name: "Follow"
  has_many :followings, through: :following_relationships, source: :following

  after_create :create_profile

  private
  def create_profile
    profile = self.build_profile
    profile.save
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
    def create
      @follow = Follow.create(follower_id: current_user.id, following_id: params[:id])
  
      if @follow.save
        redirect_to root_path, notice: 'You are now following this user.'
      else
        redirect_to root_path, alert: 'Failed to follow this user.'
      end
    end
  
    def destroy
      @follow = Follow.find_by(follower_id: current_user.id, following_id: params[:id])
  
      if @follow
        @follow.destroy
        redirect_to root_path, notice: 'You have unfollowed this user.'
      else
        redirect_to root_path, alert: 'Failed to unfollow this user.'
      end
    end
  end
  

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = Post.where(user_id: [current_user.followings.pluck(:id), current_user.id].flatten.uniq)
    .eager_load(user: :profile)
    .order(created_at: :desc)
    @users_to_follow = User.where.not(id: current_user.followings.pluck(:id)).eager_load(:profile)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_post, only: [:update, :destroy]

    def create
        @post = current_user.posts.new(post_params)
        if @post.save
            redirect_to root_path, notice: 'Post was successfully created.'
        end
    end

    def update
        if @post.update(post_params)
            redirect_to root_path, notice: 'Post was successfully updated.'
        end
    end

    def destroy
        @post.destroy
        redirect_to posts_url, notice: 'Post was successfully destroyed.'
    end

    private
    def set_post
        @post = Post.find(params[:id])
    end

    def post_params
        params.require(:post).permit(:title, :content)
    end
end
  

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :authenticate_user

    def update
        @profile.update(profile_params)
    end

    private

    def profile_params
        params.require(:profile).permit(:full_name, :user_name, :contact_number, :age, :gender)
    end

    def profile
        @profile = current_user.profile
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweetyfiy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="icon" type="image/x-icon" href="<%= asset_path("icons/favicon_io/favicon.ico") %>" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.tiny.cloud/1/<%= Rails.application.credentials.tiny_mce[:free_api_key] %>/tinymce/7/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.slim.min.js" integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/partials/_left_most_container.html.erb
<div class="col-md-3 py-3">
  <div class="brand-image text-center mb-3">
    <%= image_tag asset_path('tweetyfiy.jpeg'), alt: "Tweetyfiy Img", class: "rounded-circle", style: "width: 100px;" %>
  </div>
  <%= link_to "Logout", destroy_user_session_path, data: { "turbo-method": :delete }, class: "btn btn-primary text-left text-white w-100 my-1 position-relative" %>
  <div class="d-flex align-items-center">
    <img src="<%= asset_path('tweetyfiy.jpg') %>" alt="Profile Picture" class="rounded-circle me-2" style="width: 35px;">
    <p><%= current_user.profile.user_name || current_user.email %></p>
  </div>
</div>

app/views/partials/_middle_container.html.erb
<div class="col-md-6 py-3 overflow-auto" style="max-height: 100vh;">
    <div class="card bg-light mb-3">
        <div class="card-body">
            <h5 class="card-title">Create Post</h5>
            <%= form_with scope: :post, url: posts_path do |form| %>
                <div class="form-group">
                  <%= form.text_area :content, class: "form-control tinymce", rows: 3, placeholder: "What is happening?" %>
                </div>
                <div class="form-group">
                  <%= form.submit "Post", class: "btn btn-primary mt-2" %>
                </div>
            <% end %>
        </div>
    </div>
    <% @posts.each do |post| %>
        <div class="card text-bg-white mb-3 p-3">
          <div class="card-header d-flex justify-content-between align-items-center">
            <h5><%= post.user.profile.user_name || post.user.email %></h5>
            <% if post.user == current_user %>
              <div class="btn-group">
                <%= button_to "Delete", post_path(post), method: :delete, class: "btn btn-danger btn-sm", data: { confirm: "Are you sure?" } %>
              </div>
            <% end %>
          </div>
          <div class="card-body">
            <p class="card-text"><%= post.content.html_safe %></p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
          </div>
        </div>
    <% end %>      
</div>

app/views/partials/_right_most_container.html.erb
<div class="col-md-3 py-3">
  <h5 class="text-center">People you may know</h5>
  <div class="overflow-auto" style="max-height: 80vh;">
    <% @users_to_follow.each do |user| %>
      <div class="card mb-3">
        <div class="card-body d-flex justify-content-between align-items-center">
          <h6 class="card-title text-truncate text-decoration-none">
            <%= link_to user.profile.user_name || user.email, "#", class: "text-dark", style: "font-weight: bold; color: #007bff;" %>
          </h6>
          <%= button_to "Follow", follows_url(id: user.id), method: :post, class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>